import type {ClassId, SkillId} from '../../shared/types.js';

/** Shared presentation metadata and authoritative combat limits. */
export interface SkillDefinition {
  id: SkillId; classId: ClassId; slot: '1' | '2' | '3' | '4'; name: string; description: string;
  unlockLevel:number;kind:'attack'|'mobility'|'defense'|'support'|'control'|'channel';effectDuration?:number;cooldownFamily?:'mobility';
  manaCost: number; cooldown: number; durationScale: number; hitFraction: number;
  damageScale: number; range: number; radius?: number; halfAngle?: number;
  maxTargets: number; projectileSpeed?: number;
}
export const SKILLS: Readonly<Record<SkillId, Readonly<SkillDefinition>>> = Object.freeze({
  'warrior-cleave': {id:'warrior-cleave',unlockLevel:1,kind:'attack',classId:'warrior',slot:'1',name:'Рассечение',description:'Удар сектором перед собой, до 3 целей.',manaCost:9,cooldown:0,durationScale:1.05,hitFraction:.52,damageScale:1.13,range:2.25,halfAngle:.78,maxTargets:3},
  'warrior-whirlwind': {id:'warrior-whirlwind',unlockLevel:3,kind:'attack',classId:'warrior',slot:'2',name:'Вихрь',description:'Круговой удар по 4 ближайшим целям.',manaCost:12,cooldown:0,durationScale:1.2,hitFraction:.58,damageScale:.95,range:2.5,halfAngle:Math.PI,maxTargets:4},
  'archer-piercing': {id:'archer-piercing',unlockLevel:1,kind:'attack',classId:'archer',slot:'1',name:'Пробивная стрела',description:'Стрела проходит сквозь 3 цели на одной линии.',manaCost:12,cooldown:0,durationScale:1.15,hitFraction:.48,damageScale:1.15,range:6.5,maxTargets:3,projectileSpeed:15},
  'archer-volley': {id:'archer-volley',unlockLevel:3,kind:'attack',classId:'archer',slot:'2',name:'Веерный залп',description:'Три расходящиеся стрелы, каждая цель поражается один раз.',manaCost:14,cooldown:0,durationScale:1.25,hitFraction:.54,damageScale:.78,range:5.8,halfAngle:.27,maxTargets:3,projectileSpeed:13},
  'mage-fireball': {id:'mage-fireball',unlockLevel:1,kind:'attack',classId:'mage',slot:'1',name:'Огненный шар',description:'Снаряд и взрыв радиусом 1,65, до 4 целей.',manaCost:17,cooldown:0,durationScale:1.2,hitFraction:.52,damageScale:1.1,range:5.8,radius:1.65,maxTargets:4,projectileSpeed:9},
  'mage-frost': {id:'mage-frost',unlockLevel:3,kind:'attack',classId:'mage',slot:'2',name:'Морозный импульс',description:'Волна вокруг мага: до 4 целей, замедление на 2 секунды.',manaCost:18,cooldown:0,durationScale:1.3,hitFraction:.62,damageScale:.92,range:2.5,halfAngle:Math.PI,maxTargets:4},
  'warrior-thrust': {id:'warrior-thrust',unlockLevel:5,kind:'attack',classId:'warrior',slot:'3',name:'Выпад',description:'Сильный узкий выпад по одной цели перед собой.',manaCost:10,cooldown:0,durationScale:1.15,hitFraction:.57,damageScale:1.3,range:3,halfAngle:.33,maxTargets:1},
  'warrior-shockwave': {id:'warrior-shockwave',unlockLevel:22,kind:'attack',classId:'warrior',slot:'4',name:'Ударная волна',description:'Узкая волна земли впереди, до 4 целей.',manaCost:22,cooldown:9,durationScale:1.4,hitFraction:.67,damageScale:1.5,range:4.2,halfAngle:.36,maxTargets:4},
  'archer-frost-shot': {id:'archer-frost-shot',unlockLevel:5,kind:'attack',classId:'archer',slot:'3',name:'Морозная стрела',description:'Одна дальняя стрела замедляет цель на 2,5 секунды.',manaCost:12,cooldown:0,durationScale:1.2,hitFraction:.52,damageScale:1.13,range:7.2,maxTargets:1,projectileSpeed:14},
  'archer-rain': {id:'archer-rain',unlockLevel:22,kind:'attack',classId:'archer',slot:'4',name:'Дождь стрел',description:'Через 0,45 с поражает до 4 целей в области впереди.',manaCost:26,cooldown:10,durationScale:1.45,hitFraction:.61,damageScale:1.18,range:5.3,radius:1.75,maxTargets:4},
  'mage-lightning': {id:'mage-lightning',unlockLevel:5,kind:'attack',classId:'mage',slot:'3',name:'Цепная молния',description:'Ток перескакивает между 3 близкими целями с падением урона.',manaCost:18,cooldown:0,durationScale:1.28,hitFraction:.55,damageScale:1.08,range:5.2,radius:1.9,maxTargets:3},
  'mage-meteor': {id:'mage-meteor',unlockLevel:22,kind:'attack',classId:'mage',slot:'4',name:'Метеор',description:'Через 0,7 с падает в область впереди, до 5 целей.',manaCost:38,cooldown:12,durationScale:1.6,hitFraction:.65,damageScale:1.72,range:5.1,radius:1.9,maxTargets:5},
  'warrior-heavy': {id:'warrior-heavy',classId:'warrior',slot:'1',unlockLevel:10,kind:'attack',name:'Мощный удар',description:'Тяжёлый удар сверху по одной цели.',manaCost:12,cooldown:0,durationScale:1.7,hitFraction:.55,damageScale:1.82,range:2.6,maxTargets:1,halfAngle:.5},
  'warrior-bleed': {id:'warrior-bleed',classId:'warrior',slot:'1',unlockLevel:14,kind:'attack',name:'Кровавый разрез',description:'Разрез и кровотечение на 4 с. Повтор обновляет длительность.',manaCost:9,cooldown:0,durationScale:1.15,hitFraction:.55,damageScale:1.12,range:2.45,maxTargets:1,halfAngle:.6,effectDuration:4},
  'warrior-charge': {id:'warrior-charge',classId:'warrior',slot:'1',unlockLevel:8,kind:'mobility',name:'Рывок',description:'Сближение по прямой до 5 м, останавливается об препятствия.',manaCost:10,cooldown:9,durationScale:0.65,hitFraction:.55,damageScale:0,range:5,maxTargets:0,cooldownFamily:'mobility'},
  'warrior-leap': {id:'warrior-leap',classId:'warrior',slot:'1',unlockLevel:27,kind:'mobility',name:'Боевой прыжок',description:'Прыжок до 4 м и замедление вокруг приземления.',manaCost:16,cooldown:10,durationScale:1.1,hitFraction:.55,damageScale:0.3,range:4,maxTargets:4,cooldownFamily:'mobility',radius:1.7,effectDuration:2},
  'warrior-guard': {id:'warrior-guard',classId:'warrior',slot:'1',unlockLevel:18,kind:'defense',name:'Стальная стойка',description:'На 8 с: входящий урон −30%, исходящий −15%.',manaCost:15,cooldown:22,durationScale:0.7,hitFraction:.55,damageScale:0,range:0,maxTargets:0,effectDuration:8},
  'warrior-berserk': {id:'warrior-berserk',classId:'warrior',slot:'1',unlockLevel:32,kind:'support',name:'Берсерк',description:'На 8 с: скорость атак +22%, получаемый урон +20%.',manaCost:18,cooldown:25,durationScale:0.7,hitFraction:.55,damageScale:0,range:0,maxTargets:0,effectDuration:8},
  'warrior-shout': {id:'warrior-shout',classId:'warrior',slot:'1',unlockLevel:38,kind:'support',name:'Боевой клич',description:'Аура: урон +8%, резерв 20% максимальной маны. Повтор выключает.',manaCost:6,cooldown:2,durationScale:0.75,hitFraction:.55,damageScale:0,range:0,maxTargets:0,effectDuration:86400},
  'warrior-banner': {id:'warrior-banner',classId:'warrior',slot:'1',unlockLevel:45,kind:'defense',name:'Знамя стойкости',description:'Зона на 12 с: получаемый урон −20% в радиусе 3 м.',manaCost:20,cooldown:28,durationScale:0.9,hitFraction:.55,damageScale:0,range:0,maxTargets:0,radius:3,effectDuration:12},
  'archer-aimed': {id:'archer-aimed',classId:'archer',slot:'1',unlockLevel:10,kind:'attack',name:'Прицельный выстрел',description:'Долгая подготовка, один сильный точный выстрел.',manaCost:14,cooldown:0,durationScale:1.7,hitFraction:.55,damageScale:1.82,range:7,maxTargets:1,projectileSpeed:18},
  'archer-poison': {id:'archer-poison',classId:'archer',slot:'1',unlockLevel:14,kind:'attack',name:'Ядовитая стрела',description:'Одна стрела и яд на 4 с. Повтор обновляет длительность.',manaCost:10,cooldown:0,durationScale:1.2,hitFraction:.55,damageScale:1.12,range:6.5,maxTargets:1,projectileSpeed:15,effectDuration:4},
  'archer-retreat': {id:'archer-retreat',classId:'archer',slot:'1',unlockLevel:8,kind:'mobility',name:'Отскок',description:'Отход на 4,5 м назад от направления прицеливания.',manaCost:10,cooldown:9,durationScale:0.7,hitFraction:.55,damageScale:0,range:4.5,maxTargets:0,cooldownFamily:'mobility'},
  'archer-roll': {id:'archer-roll',classId:'archer',slot:'1',unlockLevel:27,kind:'mobility',name:'Перекат',description:'Короткий перекат на 3,5 м в выбранном направлении.',manaCost:9,cooldown:9,durationScale:0.65,hitFraction:.55,damageScale:0,range:3.5,maxTargets:0,cooldownFamily:'mobility'},
  'archer-trap': {id:'archer-trap',classId:'archer',slot:'1',unlockLevel:18,kind:'control',name:'Капкан',description:'Ловушка на 15 с: обездвиживает первую цель на 2 с.',manaCost:14,cooldown:18,durationScale:0.8,hitFraction:.55,damageScale:0.35,range:3,maxTargets:1,radius:1,effectDuration:15},
  'archer-focus': {id:'archer-focus',classId:'archer',slot:'1',unlockLevel:32,kind:'support',name:'Сосредоточенность',description:'До движения: одиночный урон +12%, точность +5%, подготовка +10%.',manaCost:8,cooldown:2,durationScale:0.85,hitFraction:.55,damageScale:0,range:0,maxTargets:0,effectDuration:86400},
  'archer-wind': {id:'archer-wind',classId:'archer',slot:'1',unlockLevel:38,kind:'support',name:'Попутный ветер',description:'Скорость перемещения +20% на 12 с.',manaCost:14,cooldown:25,durationScale:0.75,hitFraction:.55,damageScale:0,range:0,maxTargets:0,effectDuration:12},
  'archer-smoke': {id:'archer-smoke',classId:'archer',slot:'1',unlockLevel:45,kind:'defense',name:'Дымовая завеса',description:'Область на 8 с: точность атакующих из дыма снижена.',manaCost:20,cooldown:24,durationScale:0.9,hitFraction:.55,damageScale:0,range:0,maxTargets:0,radius:3,effectDuration:8},
  'mage-ice-lance': {id:'mage-ice-lance',classId:'mage',slot:'1',unlockLevel:10,kind:'attack',name:'Ледяное копьё',description:'Один ледяной снаряд с замедлением на 1,5 с.',manaCost:14,cooldown:0,durationScale:1.2,hitFraction:.55,damageScale:1.3,range:6.5,maxTargets:1,projectileSpeed:16,effectDuration:1.5},
  'mage-beam': {id:'mage-beam',classId:'mage',slot:'1',unlockLevel:14,kind:'channel',name:'Чародейский луч',description:'Удерживайте: одиночный луч. Каждый тик тратит ману; движение прерывает.',manaCost:5,cooldown:0,durationScale:0.5,hitFraction:.55,damageScale:0.48,range:5.5,maxTargets:1},
  'mage-teleport': {id:'mage-teleport',classId:'mage',slot:'1',unlockLevel:8,kind:'mobility',name:'Телепортация',description:'Перенос до 4 м по свободной линии, без прохода сквозь стены.',manaCost:14,cooldown:10,durationScale:0.6,hitFraction:.55,damageScale:0,range:4,maxTargets:0,cooldownFamily:'mobility'},
  'mage-ice-step': {id:'mage-ice-step',classId:'mage',slot:'1',unlockLevel:27,kind:'mobility',name:'Ледяной шаг',description:'Скольжение до 4 м с коротким замедляющим следом.',manaCost:16,cooldown:10,durationScale:0.8,hitFraction:.55,damageScale:0,range:4,maxTargets:0,cooldownFamily:'mobility',radius:.8,effectDuration:3},
  'mage-mana-shield': {id:'mage-mana-shield',classId:'mage',slot:'1',unlockLevel:18,kind:'defense',name:'Мановый щит',description:'8 с: 35% урона вместо HP тратит MP; запас поглощения ограничен.',manaCost:12,cooldown:22,durationScale:0.75,hitFraction:.55,damageScale:0,range:0,maxTargets:0,effectDuration:8},
  'mage-seals': {id:'mage-seals',classId:'mage',slot:'1',unlockLevel:32,kind:'control',name:'Кольцо печатей',description:'Прерывает и обездвиживает 4 близких цели на 1,5 с.',manaCost:20,cooldown:20,durationScale:1,hitFraction:.55,damageScale:0.45,range:2.5,maxTargets:4,halfAngle:Math.PI,effectDuration:1.5},
  'mage-ward': {id:'mage-ward',classId:'mage',slot:'1',unlockLevel:38,kind:'defense',name:'Чародейский покров',description:'Получаемый урон −18% на 10 с. Защита не складывается.',manaCost:16,cooldown:24,durationScale:0.8,hitFraction:.55,damageScale:0,range:0,maxTargets:0,effectDuration:10},
  'mage-mana-source': {id:'mage-mana-source',classId:'mage',slot:'1',unlockLevel:45,kind:'support',name:'Источник маны',description:'Область на 10 с возвращает до 24 MP; 1 источник на мага.',manaCost:18,cooldown:30,durationScale:1,hitFraction:.55,damageScale:0,range:0,maxTargets:0,radius:3,effectDuration:10},
});
export const skillsForClass=(classId: ClassId): readonly Readonly<SkillDefinition>[] => Object.values(SKILLS).filter(skill=>skill.classId===classId).sort((a,b)=>a.unlockLevel-b.unlockLevel);
export const legacySkillId=(classId: ClassId): SkillId => classId==='warrior'?'warrior-whirlwind':classId==='archer'?'archer-piercing':'mage-fireball';
