/** DOM IDs shared by the game and model workshops. Fail early on missing markup. */
const elementTags = {
  'angle': 'input',
  'attack': 'button',
  'bag-count': 'span',
  'bag-items': 'div',
  'boss-goal': 'li',
  'camp-goal': 'li',
  'character-class': 'p',
  'character-close': 'button',
  'character-level': 'b',
  'character-name': 'h3',
  'character-panel': 'aside',
  'character-title': 'h2',
  'character-toggle': 'button',
  'character-xp': 'span',
  'character-xp-fill': 'i',
  'chat-form': 'form',
  'chat-input': 'input',
  'chat-lines': 'div',
  'chat-panel': 'aside',
  'claim-items': 'button',
  'class-emblem': 'div',
  'class-role': 'p',
  'clips': 'div',
  'connection': 'button',
  'cooldown': 'i',
  'creature': 'select',
  'creature-name': 'h1',
  'death-screen': 'div',
  'dungeon-progress': 'aside',
  'dungeon-objective': 'h2',
  'dungeon-hint': 'p',
  'derived-stats': 'dl',
  'equipment-figure': 'div',
  'equipment-slots': 'div',
  'hero-details': 'p',
  'hero-level': 'b',
  'hp-fill': 'i',
  'hp-orb': 'div',
  'hp-text': 'span',
  'hud-experience': 'div',
  'hud-xp-fill': 'i',
  'hud-xp-text': 'span',
  'hurt-vignette': 'div',
  'inventory-close': 'button',
  'inventory-gold': 'span',
  'inventory-panel': 'aside',
  'inventory-status': 'span',
  'inventory-title': 'h2',
  'inventory-toggle': 'button',
  'join-class': 'select',
  'join-error': 'p',
  'join-form': 'form',
  'join-name': 'input',
  'join-panel': 'section',
  'join-submit': 'button',
  'kills-goal': 'li',
  'level-reward': 'span',
  'load-progress': 'p',
  'loading': 'div',
  'mana-fill': 'i',
  'mana-orb': 'div',
  'mana-potion': 'button',
  'mana-potions': 'b',
  'mana-text': 'span',
  'minimap': 'canvas',
  'location-name': 'h1',
  'map-legend': 'div',
  'forest-quest': 'aside',
  'stadium-guide': 'aside',
  'movement': 'button',
  'movement-label': 'span',
  'notice': 'div',
  'pause': 'button',
  'performance': 'span',
  'portrait': 'canvas',
  'potion': 'button',
  'potions': 'b',
  'preview-label': 'span',
  'quest-hint': 'p',
  'reset': 'button',
  'camp-return-label': 'span',
  'loot-labels-toggle': 'button',
  'sound-toggle': 'button',
  'reset-confirm': 'div',
  'reset-confirm-no': 'button',
  'reset-confirm-yes': 'button',
  'reset-stats': 'button',
  'retry': 'button',
  'scene': 'canvas',
  'special': 'button',
  'skill-secondary': 'button',
  'skill-tertiary': 'button',
  'skill-quaternary': 'button',
  'skill-quinary': 'button',
  'skill-mouse': 'button',
  'afk-toggle': 'button',
  'afk-status': 'span',
  'afk-xp-rate': 'span',
  'stat-apply': 'button',
  'stat-cancel': 'button',
  'stat-points': 'b',
  'stat-rows': 'div',
  'stat-status': 'p',
  'status': 'p',
  'target-fill': 'i',
  'target-health': 'small',
  'target-name': 'span',
  'target-panel': 'div',
  'timeline': 'input',
  'unspent-badge': 'b',
  'version': 'select',
  'version-field': 'label',
  'weapon': 'select',
  'world-ui': 'div',
  'zone-state': 'span',
} as const;
type UiId = keyof typeof elementTags;
type UiElement<Id extends UiId> = HTMLElementTagNameMap[typeof elementTags[Id]];

export function element<Id extends UiId>(id: Id): UiElement<Id>;
export function element(id: string): HTMLElement;
export function element(id: string): HTMLElement {
  const node = document.getElementById(id);
  if (!(node instanceof HTMLElement)) throw new Error(`Missing interface element: ${id}`);
  const expected = elementTags[id as UiId];
  if (expected && node.tagName.toLowerCase() !== expected) throw new Error(`Unexpected interface element: ${id}`);
  return node;
}

export const errorMessage = (error: unknown): string => error instanceof Error ? error.message : String(error);
